### PR TITLE
Switch cli to click

### PR DESCRIPTION
**Pull request by guilhermef**
This change is needed to enable configuring the service via environment variables.

It will make it easier to support parameters from Secrets and ConfigMaps in Kubernetes.

### CODE REVIEW

**Comment by RaphaelVRossi** [comment]
Hey @guilhermef

After this change we had a downgrade regarding the "extra_args" attribute, it is no longer working as expected.
For example:

```shell
$ remotecv test=1
Usage: remotecv [OPTIONS]
Try 'remotecv --help' for help.

Error: Got unexpected extra argument (test=1)
```

**Comment by guilhermef** [comment]
Hey @RaphaelVRossi the `extra_args` were only being used by Celery, so it was moved to a specific parameter `celery_commands `.

https://github.com/thumbor/remotecv/blob/cdafb9dc06bd5ffc30e71096436c5b29b1e218f6/remotecv/worker.py#L57

**Comment by RaphaelVRossi** [comment]
In this PR #63, we created a `BaseMetrics` class, with a `config` parameter.

If someone tries to create a new metric extension, they will not be able to use other settings like `port` or `host` for this new extension.

Example:

```python
class BaseMetrics:
    def __init__(self, config):
        self.config = config
[...]

class PrometheusMetrics:
    def __init__(self, config):
        self.config = config
        self.port. = self.config['prometheus_port'] #something like that.
[...]
```

And use like:
```shell
remotecv prometheus_port=8800
```

**Comment by guilhermef** [comment]
I would extend the existing parameters to support metrics config, but I would avoid using `extra_args` for this.

**Comment by RaphaelVRossi** [comment]
I'm wondering if we should still support arguments, or if we should only use environment variables, with `pydantic`.

It will be better to run inside a container.

**Comment by guilhermef** [comment]
We support both arguments and environment variables with Click now.

**Pull request merged**
